services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: peacelife-home-assistant
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/config
